description=Lemmatizer token filter
version=${project.version}
name=elasticsearch-analysis-lemmagen
classname=org.elasticsearch.plugin.analysis.lemmagen.AnalysisLemmagenPlugin
java.version=17
elasticsearch.version=${project.version}
